/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Education = IDL.Record({
  'certificate' : IDL.Opt(ExternalBlob),
  'institution' : IDL.Text,
  'degree' : IDL.Text,
  'yearGraduated' : IDL.Nat,
});
export const WorkExperience = IDL.Record({
  'description' : IDL.Text,
  'company' : IDL.Text,
  'position' : IDL.Text,
  'durationInMonths' : IDL.Nat,
});
export const Time = IDL.Int;
export const Skill = IDL.Record({ 'name' : IDL.Text, 'level' : IDL.Text });
export const CertificationForm = IDL.Record({
  'cv' : IDL.Opt(ExternalBlob),
  'id' : IDL.Text,
  'portfolio' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'education' : IDL.Vec(Education),
  'workExperience' : IDL.Vec(WorkExperience),
  'email' : IDL.Text,
  'additionalFiles' : IDL.Vec(ExternalBlob),
  'timestamp' : Time,
  'skills' : IDL.Vec(Skill),
});
export const CertificationFormInput = IDL.Record({
  'cv' : IDL.Opt(ExternalBlob),
  'portfolio' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'education' : IDL.Vec(Education),
  'workExperience' : IDL.Vec(WorkExperience),
  'email' : IDL.Text,
  'additionalFiles' : IDL.Vec(ExternalBlob),
  'skills' : IDL.Vec(Skill),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getForms' : IDL.Func([], [IDL.Vec(CertificationForm)], ['query']),
  'submitForm' : IDL.Func([CertificationFormInput], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Education = IDL.Record({
    'certificate' : IDL.Opt(ExternalBlob),
    'institution' : IDL.Text,
    'degree' : IDL.Text,
    'yearGraduated' : IDL.Nat,
  });
  const WorkExperience = IDL.Record({
    'description' : IDL.Text,
    'company' : IDL.Text,
    'position' : IDL.Text,
    'durationInMonths' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Skill = IDL.Record({ 'name' : IDL.Text, 'level' : IDL.Text });
  const CertificationForm = IDL.Record({
    'cv' : IDL.Opt(ExternalBlob),
    'id' : IDL.Text,
    'portfolio' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'education' : IDL.Vec(Education),
    'workExperience' : IDL.Vec(WorkExperience),
    'email' : IDL.Text,
    'additionalFiles' : IDL.Vec(ExternalBlob),
    'timestamp' : Time,
    'skills' : IDL.Vec(Skill),
  });
  const CertificationFormInput = IDL.Record({
    'cv' : IDL.Opt(ExternalBlob),
    'portfolio' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'education' : IDL.Vec(Education),
    'workExperience' : IDL.Vec(WorkExperience),
    'email' : IDL.Text,
    'additionalFiles' : IDL.Vec(ExternalBlob),
    'skills' : IDL.Vec(Skill),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getForms' : IDL.Func([], [IDL.Vec(CertificationForm)], ['query']),
    'submitForm' : IDL.Func([CertificationFormInput], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };